services:
  db:
    platform: linux/arm64/v8
    image: mysql:8.4
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: hongpoong
      MYSQL_ROOT_PASSWORD: 1234

      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: