FROM openjdk:21-slim

ARG PROFILE
ARG DB_URL_PROD
ARG DB_USERNAME_PROD
ARG DB_PASSWORD_PROD
ARG LOKI_URL

COPY build/libs/Hongpoong-0.0.1-SNAPSHOT.jar app.jar

ENV PROFILE=${PROFILE}
ENV DB_URL_PROD=${DB_URL_PROD}
ENV DB_USERNAME_PROD=${DB_USERNAME_PROD}
ENV DB_PASSWORD_PROD=${DB_PASSWORD_PROD}
ENV LOKI_URL=${LOKI_URL}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=${PROFILE}", "/app.jar"]