spring:
  application:
    name: Hongpoong
  profiles:
    active: local
    include: secret
#    include: secret의 mysql 설정정보 가져옴
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true