spring:
  application:
    name: Hongpoong
  profiles:
    include: database
#    active: local

  jpa:
#    sql보기 및 포맷팅
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  port: 8080