spring:
  application:
    name: Hongpoong
  profiles:
    include: secret
    active: local
  jpa:
#    sql보기 및 포맷팅
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
server:
  port: 8080