### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=dompoo&password=1234&remember-me=1


### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "dompoo",
  "password1": "1234",
  "password2": "1234"
}


### 메인페이지

GET http://localhost:8080


### 사용자페이지

GET http://localhost:8080/user


### 관리자페이지

GET http://localhost:8080/admin


### 기본

GET http://localhost:8080/reservation