### 예약 추가
POST {{url}}/reservation
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "date": "2024-09-16",
  "type": "FIXED_TIME",
  "startTime": "TIME_1600",
  "endTime": "TIME_1700",
  "participaterIds": [1, 2, 3],
  "message": "산틀 정공 연습",
  "participationAvailable": true
}

### 연도/달 예약 조회
GET {{url}}/reservation/year-month?
    year=2025&
    month=10
Authorization: Bearer {{jwtToken}}

### 연도/달 예약 조회
GET {{url}}/reservation/day?
    date=2025-09-20
Authorization: Bearer {{jwtToken}}

### 오늘의 해야할 예약 조회
GET {{url}}/reservation/todo
Authorization: Bearer {{jwtToken}}

### 예약 상세 조회
GET {{url}}/reservation/1
Authorization: Bearer {{jwtToken}}

### 예약 시간 연장
PATCH {{url}}/reservation/2/extend
Authorization: Bearer {{jwtToken}}

### 예약 종료
POST {{url}}/reservation/2/end
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "endImages": ["image1", "image2"]
}

### 예약 수정
PATCH {{url}}/reservation/2
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "date": "2024-10-17",
  "startTime": "TIME_1000",
  "endTime": "TIME_1200",
  "message": "산틀 정공 연습 아님",
  "addedParticipatorIds": [2],
  "removedParticipatorIds": [1]
}

### 예약 삭제
DELETE {{url}}/reservation/2
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

### 예약 종료 후 상세 조회
GET {{url}}/reservation/manage/2
Authorization: Bearer {{jwtToken}}

### 어드민 예약 수정
PATCH {{url}}/reservation/manage/2
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "date": "2024-10-17",
  "startTime": "TIME_1000",
  "endTime": "TIME_1200",
  "message": "산틀 정공 연습 아님",
  "addedParticipatorIds": [2],
  "removedParticipatorIds": [1]
}

### 어드민 예약 삭제
DELETE {{url}}/reservation/manage/2
Authorization: Bearer {{jwtToken}}
Content-Type: application/json